{% set name = "match-series" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/berkels/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ae2c867cc721e0dccc0be2e57d03251f26a084ea522eb456efe39994dee0f0ad
  patches:
    - quocmesh.patch 

build:
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
  host:
    - libblas
    - liblapack
    - fftw
    - libpng
    - zlib
    - bzip2  # [not win]
    - libtiff
    - suitesparse
    - metis  # [win]
  run:
    - libpng

test:
  files:
    - matchSeries.par
    - testImg_0_STEM.tif
    - testImg_1_STEM.tif
    - testImg_2_STEM.tif
    - testImg_3_STEM.tif
  commands:
    - set QUOC_NO_SYSTEM_PAUSE=ON  # [win]
    - matchSeries

about:
  home: https://github.com/berkels/match-series
  license: CDDL-1.0
  license_file: LICENSE.txt
  summary: Joint non-rigid registration and reconstruction of image series

  description: |
    Joint non-rigid registration and reconstruction of image series
  doc_url: https://github.com/berkels/match-series
  dev_url: https://github.com/berkels/match-series

extra:
  recipe-maintainers:
    - jan-janssen
    - din14970
    - berkels
